In [1]:
# Indexação e Fatiamento de arrays

import numpy as np

In [2]:
arr = np.arange(0, 30, 3)
print(arr)
print(arr[3])
print(arr[2:5])
print(arr[:5])
print(arr[2:])

[ 0  3  6  9 12 15 18 21 24 27]
9
[ 6  9 12]
[ 0  3  6  9 12]
[ 6  9 12 15 18 21 24 27]


In [3]:
arr[2:] = 100
print(arr)

[  0   3 100 100 100 100 100 100 100 100]


In [4]:
arr = np.arange(50).reshape((5,10))
print(arr)
print(arr.shape)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
(5, 10)


In [5]:
arr[:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [6]:
arr2 = arr[:3].copy()
arr2[:] = 100
print(f'{arr} \n {arr2}')

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]] 
 [[100 100 100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100 100 100]]


In [7]:
arr[1:4,5:]

array([[15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29],
       [35, 36, 37, 38, 39]])

In [8]:
bol = arr > 25
print(bol)

[[False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]]


In [9]:
arr[bol]

array([26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49])

In [10]:
array = np.linspace(0, 100, 30)
print(array.shape)
array = array.reshape(3, 10)
print(array)

(30,)
[[  0.           3.44827586   6.89655172  10.34482759  13.79310345
   17.24137931  20.68965517  24.13793103  27.5862069   31.03448276]
 [ 34.48275862  37.93103448  41.37931034  44.82758621  48.27586207
   51.72413793  55.17241379  58.62068966  62.06896552  65.51724138]
 [ 68.96551724  72.4137931   75.86206897  79.31034483  82.75862069
   86.20689655  89.65517241  93.10344828  96.55172414 100.        ]]


In [11]:
print(array[0:2, 2])

[ 6.89655172 41.37931034]
