# Array

* Funciona para criar arrays de uma ou várias dimensões

In [1]:
import numpy as np

minha_lista = [1, 2, 3]

print(minha_lista)

[1, 2, 3]


In [3]:
minha_lista = [1, 2, 3]

np.array(minha_lista) #Array de uma dimensão

array([1, 2, 3])

In [4]:
minha_matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

np.array(minha_matriz)  #Array de três dimensões

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Arange

* Funciona como o metodo range utilizado para criar uma sequência de número, mas neste casa cria um array

In [5]:
import numpy as np

print(np.arange(0, 10))

print(np.arange(0, 10, 2))

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


# Zeros

* Criar um array com números zeros

In [6]:
import numpy as np


print(np.zeros(3))

print(np.zeros((5, 5)))

[0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


# Ones
* Criar um array com números um

In [7]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# Eye

* Criar uma matriz de identidade

In [8]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Linspace

* Semelhante ao arange, a diferença é que:
    * No arange a gente especifica o número inicial, final e o intervalo
    * No linspace a gente especifica o inicio da serie, fim da serie, quantos número queremos ver igualmentes passados na serie

In [9]:
import numpy as np

n1 = np.linspace(0, 10, 1)
n2 = np.linspace(0, 10, 2)
n3 = np.linspace(0, 10, 3)
n4 = np.linspace(0, 25, 3)

print(n1)
print(n2)
print(n3)
print(n4)

[0.]
[ 0. 10.]
[ 0.  5. 10.]
[ 0.  12.5 25. ]


# Random
* O random vai criar números aleatórios

In [10]:
import numpy as np

print(np.random.rand(5)) #Apenas numeros entre 0 e 1
print(np.random.rand(5) * 100) #Apenas numeros entre 0 e 100
print(np.random.rand(5, 4)) #Criando matriz de números aleatorios entre 0 e 1, com 5 linhas e 4 colunas 5x4
print(np.random.rand(5, 4, 3)) #Criando matriz de números aleatorios entre 0 e 1, com 5 linhas e 4 colunas 5x4 e 3 dimensões

[0.21615177 0.92192652 0.13114842 0.2013209  0.64977424]
[32.51313596 30.87798606 50.80200883 95.05451461 65.49239061]
[[0.53480861 0.03909286 0.84764956 0.43154528]
 [0.49501911 0.01307101 0.19398017 0.30996177]
 [0.86258203 0.25277484 0.76435568 0.50916092]
 [0.58369525 0.74376941 0.07225617 0.13128096]
 [0.23900672 0.94853785 0.08221448 0.55469464]]
[[[0.95777153 0.39675849 0.23298302]
  [0.17054096 0.13379125 0.60223023]
  [0.14666089 0.68382882 0.25216129]
  [0.60900284 0.97365451 0.69349058]]

 [[0.97527197 0.47581976 0.16753237]
  [0.04124748 0.73730209 0.09719254]
  [0.85847391 0.5593349  0.36770539]
  [0.52732577 0.11541005 0.26216552]]

 [[0.48701903 0.3096726  0.78661516]
  [0.97122421 0.26945047 0.36877998]
  [0.67368207 0.70701793 0.39743294]
  [0.54365167 0.92041631 0.92208279]]

 [[0.945776   0.2358423  0.47506315]
  [0.92973707 0.7335803  0.36858183]
  [0.85581156 0.11943817 0.75351181]
  [0.6467633  0.01563329 0.54130959]]

 [[0.89640531 0.08066436 0.41082449]
  [0.557

# Randn
* Vai retornar números aleatorios, mas esses números não são tirados de uma distribuíção uniforma, são tirados de uma distribuição normal, média 0 induzindo padrão 1

In [14]:
import numpy as np

print(np.random.randn(4))

[-1.13374996 -0.97884007 -0.31287204  0.78194446]


In [16]:
import numpy as np

print(np.random.randint(0, 100, 10)) #números aleatorios inteiros

[96 25 75 78 54 81 71 84 28 83]


In [17]:
import numpy as np

arr = np.random.rand(25) #array de tamanho 25

print(arr)

print(arr.shape)

[0.89962896 0.6411463  0.00702869 0.16513166 0.26551973 0.26874467
 0.71745801 0.43758559 0.89385228 0.03313704 0.50076318 0.53445815
 0.01259962 0.06783771 0.95736548 0.23053605 0.20975878 0.33761765
 0.20092149 0.51559416 0.60026825 0.18604339 0.3946293  0.3056122
 0.52292594]
(25,)


In [18]:
arr = arr.reshape((5, 5)) #array de 5x5

print(arr)

print(arr.shape)

print(arr.max()) #maior número do array
print(arr.min()) #menor número do array
print(arr.argmax()) #O indice do maior número do array
print(arr.argmin()) #O indice do menor número do array

[[0.89962896 0.6411463  0.00702869 0.16513166 0.26551973]
 [0.26874467 0.71745801 0.43758559 0.89385228 0.03313704]
 [0.50076318 0.53445815 0.01259962 0.06783771 0.95736548]
 [0.23053605 0.20975878 0.33761765 0.20092149 0.51559416]
 [0.60026825 0.18604339 0.3946293  0.3056122  0.52292594]]
(5, 5)
0.957365479348093
0.007028689092734797
14
2
