# Array

* Funciona para criar arrays de uma ou várias dimensões

In [1]:
import numpy as np

minha_lista = [1, 2, 3]

print(minha_lista)

[1, 2, 3]


In [9]:
import numpy as npz
minha_lista = [1, 2, 3]

np.array(minha_lista) #Array de uma dimensão

minha_matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

np.array(minha_matriz)  #Array de três dimensões

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Arange

* Funciona como o metodo range utilizado para criar uma sequência de número, mas neste casa cria um array

In [2]:
import numpy as np

print(np.arange(0, 10))

print(np.arange(0, 10, 2))

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


# Zeros

* Criar um array com números zeros

In [17]:
import numpy as np


print(np.zeros(3))

print(np.zeros((5, 5)))

[0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


# Ones
* Criar um array com números um

In [19]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# Eye

* Criar uma matriz de identidade

In [20]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Linspace

* Semelhante ao arange, a diferença é que:
    * No arange a gente especifica o número inicial, final e o intervalo
    * No linspace a gente especifica o inicio da serie, fim da serie, quantos número queremos ver igualmentes passados na serie

In [7]:
import numpy as np

n1 = np.linspace(0, 10, 2)
n2 = np.linspace(0, 10, 3)
n3 = np.linspace(0, 25, 3)

print(n1)
print(n2)
print(n3)

[ 0. 10.]
[ 0.  5. 10.]
[ 0.  12.5 25. ]


# Random
* O random vai criar números aleatórios

In [27]:
import numpy as np

print(np.random.rand(5)) #Apenas numeros entre 0 e 1
print(np.random.rand(5) * 100) #Apenas numeros entre 0 e 100
print(np.random.rand(5, 4)) #Criando matriz de números aleatorios entre 0 e 1, com 5 linhas e 4 colunas 5x4
print(np.random.rand(5, 4, 3)) #Criando matriz de números aleatorios entre 0 e 1, com 5 linhas e 4 colunas 5x4 e 3 dimensões

[0.9665666  0.71118921 0.3727748  0.40355944 0.6625845 ]
[22.26694733 44.18178549 59.79941491 68.791104   20.44208762]
[[0.48099391 0.30538531 0.37496963 0.47713982]
 [0.07311213 0.74803656 0.06369161 0.74374413]
 [0.76412083 0.72395175 0.51061562 0.75441245]
 [0.14528685 0.94576583 0.3089821  0.93315844]
 [0.13348843 0.74458838 0.2728633  0.48363997]]
[[[0.37453216 0.88066136 0.07051837]
  [0.02211999 0.48996223 0.75619824]
  [0.029588   0.04664943 0.9921959 ]
  [0.56625201 0.58526927 0.51836017]]

 [[0.96418608 0.21719805 0.3916909 ]
  [0.34741921 0.68541835 0.72966942]
  [0.40009142 0.67499668 0.21685045]
  [0.74808859 0.55123657 0.3036178 ]]

 [[0.59813809 0.30935111 0.09569822]
  [0.85677483 0.65615117 0.10954992]
  [0.01123788 0.05497499 0.72985233]
  [0.42642386 0.66860833 0.50950134]]

 [[0.03819219 0.93494689 0.61643316]
  [0.49670334 0.92828281 0.61410886]
  [0.50890694 0.60161    0.23904332]
  [0.92704262 0.93045673 0.10314262]]

 [[0.59588892 0.75904193 0.21477998]
  [0.897

# Randn
* Vai retornar números aleatorios, mas esses números não são tirados de uma distribuíção uniforma, são tirados de uma distribuição normal, média 0 induzindo padrão 1

In [29]:
import numpy as np

print(np.random.randn(4))

[ 0.16836936  0.35784859 -0.64089434  0.87335079]


In [8]:
import numpy as np

print(np.random.randint(0, 100, 10)) #números aleatorios inteiros

[82 65 83 83 30 73  8 55 60 40]


In [9]:
import numpy as np

arr = np.random.rand(25) #array de tamanho 25

print(arr)

print(arr.shape)

arr = arr.reshape((5, 5)) #array de 5x5

print(arr)

print(arr.shape)

print(arr.max()) #maior número do array
print(arr.min()) #menor número do array
print(arr.argmax()) #O indice do maior número do array
print(arr.argmin()) #O indice do menor número do array

[0.53504028 0.65911897 0.7785106  0.81679219 0.07463322 0.47470591
 0.31270961 0.66113815 0.71788881 0.64005682 0.18639303 0.34017893
 0.51697517 0.36983292 0.95035502 0.55496857 0.44332188 0.04665423
 0.67607832 0.22517082 0.40805092 0.47705018 0.93572029 0.5279581
 0.88857608]
(25,)
[[0.53504028 0.65911897 0.7785106  0.81679219 0.07463322]
 [0.47470591 0.31270961 0.66113815 0.71788881 0.64005682]
 [0.18639303 0.34017893 0.51697517 0.36983292 0.95035502]
 [0.55496857 0.44332188 0.04665423 0.67607832 0.22517082]
 [0.40805092 0.47705018 0.93572029 0.5279581  0.88857608]]
(5, 5)
0.9503550184120876
0.04665422848270584
14
17
